trigger:
  branches:
    exclude:
      - "*"

pr:
  branches:
    include:
      - main  # or whatever your default branch is

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'
  AWS_REGION: 'us-east-1'  # update as needed

steps:
# Install Terraform
- task: UseTerraform@0
  inputs:
    terraformVersion: '$(TF_VERSION)'

# Setup AWS credentials (via SSO or role assumption)
- task: Bash@3
  displayName: 'Configure AWS SSO or Assume Role'
  inputs:
    targetType: 'inline'
    script: |
      echo "Setting up AWS CLI for SSO..."
      # Example: login manually or configure credential process here
      # For CI: you may use OIDC or session tokens from environment or secrets
      # Skip if your agent has SSO baked in

# Checkout your code
- task: Checkout@1

# Terraform Init
- script: terraform init
  displayName: 'Terraform Init'

# Terraform Format Check
- script: terraform fmt -check
  displayName: 'Terraform Format Check'

# Terraform Validate
- script: terraform validate
  displayName: 'Terraform Validate'

# Terraform Plan
- script: terraform plan -out=tfplan.out
  displayName: 'Terraform Plan'
